name: Hugo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Hugo build by MayMeow
      uses: MayMeowHQ/Hugo-Build-Action@v5
      with:
        production-config: './production.config.toml'
        hugo-version: '0.89.2'
        hugo-sha: '8efea63ab960a91918a4c6131d10c244635cd983e4d083afdba6c6b99edb55b6'    

    # - name: Azure deploy action
    #   uses: MayMeowHQ/azure-deploy-action@v2
    #   with:
    #     azure_connection_string: ${{ secrets.AZ_STORAGE_CONNECTION_STRING }}
    #     source_dir: 'public'
